my:
  greeting: Hello World Student service from config Server
  list:
    values: One, Two, Three, Four

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/hawa'
  driverClassName: com.mysql.cj.jdbc.Driver